// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Eli_Book","status":true,"description":"♦5.3.1♦ Essential plugin for all Eli plugins.","parameters":{"engine":"{\"pixelPerfect\":\"false\",\"styleOverflow\":\"false\",\"--- MZ ONLY ---\":\"\",\"disableEffekseer\":\"false\"}","playtest":"{\"openDevTools\":\"false\",\"nwWindowPos\":\"0, 0\",\"--- MZ ONLY ---\":\"\",\"gameFocus\":\"true\",\"quickRestart\":\"true\"}"}},
{"name":"EliMZ_ButtonCommonEvents","status":true,"description":"♦5.2.3♦ Bind common events to keyboard/gamepad buttons!","parameters":{"presetKeys":"[]","presetKeysGamePad":"[]"}},
{"name":"Tyruswoo_TileControl","status":true,"description":"MZ v3.0.1 Change tiles dynamically during gameplay!","parameters":{"Tile Animation Frames":"30","Common Event on OK Press":"","Tile Info on OK Press":"true"}},
{"name":"FilterControllerMZ","status":true,"description":"FilterControllerMZ","parameters":{"decimalVariable":"true","displacementImage":"DisplacementMap","global-enable Settings":"","enabledAll-ShowInOptionMenu":"false","enabledAll-Text":"Filter Effects Enabled","enabledAll-DefaultValue":"true"}}
];
